language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests."

script:
  - docker --version # print the version for logging

jobs:
  include:
    - stage: dockerize
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        # Building & Tagging Docker Images
        - docker build -t udagram-api-feed ./udagram-api-feed
        - docker tag udagram-api-feed ocrankingsley/udagram-micro-frontend:latest
        - docker push ocrankingsley/udagram-micro-frontend:latest

        - docker build -t udagram-api-user ./udagram-api-user
        - docker tag udagram-api-user ocrankingsley / udagram-micro-backend-user:latest
        - docker push ocrankingsley/udagram-micro-backend-user:latest

        - docker build -t udagram-frontend ./udagram-frontend
        - docker tag udagram-frontend ocrankingsley/udagram-micro-backend-feed:latest
        - docker push ocrankingsley/udagram-micro-backend-feed:latest

        - docker build -t reverseproxy ./udagram-reverseproxy
        - docker tag reverseproxy ocrankingsley/udagram-micro-reverseproxy:latest
        - docker push ocrankingsley/udagram-micro-reverseproxy:latest

branches:
  only:
    - main  

after_success:
  echo "Docker Images Built & Pushed Successfully"