language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

jobs:
  include:
    - stage: dockerize
      script:
        - cd deployment/docker
        - docker-compose -f docker-compose-build.yaml build --parallel
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose -f docker-compose-build.yaml push

branches:
  only:
    - main