version: "3"
services:
  reverseproxy:
    build:
      context: ../../udagram-reverseproxy
    image: ocrankingsley/udagram-reverseproxy 
  backend_user:
    build:
      context: ../../udagram-api-user
    image: ocrankingsley/udagram-api-user
  backend_feed:
    build:
      context: ../../udagram-api-feed  
    image: ocrankingsley/udagram-api-feed
  frontend:
    build:
      context: ../../udagram-api-frontend  
    image: ocrankingsley/udagram-frontend:local