apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ocrankingsley/udagram-micro-frontend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "2G"
              cpu: "500m"
            limits:
              memory: "4G"
              cpu: "500m"
      restartPolicy: Always